In [1]:
import pandas as pd
file = 'HBW-BirdLife_Checklist_Version_3.xlsx'

In [2]:
data = pd.read_excel(file)
data.columns = data.iloc[0]
data = data.drop(0)

In [3]:
import openpyxl

wb = openpyxl.load_workbook(file)
ws = wb.active

/home/gianfranco/.local/lib/python3.5/site-packages/openpyxl/worksheet/header_footer.py:49: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [10]:
ws.cell(row=10000, column=5).hyperlink.target.split()

['http://datazone.birdlife.org/species/factsheet/103882288']

In [42]:
hyperlinks = []
for row in range(3,ws.max_row+1):
    hyperlinks.append(ws.cell(row=row, column=5).hyperlink.target)

In [45]:
data['hyperlink'] = hyperlinks

In [47]:
names = [
    'Order','Family name','Family','CommonName','ScientificName',
    'Authority','TaxonomicTreatment', 'IUCNRedListCategory','Synonyms', 
    'AlternativeCommonNames', 'TaxonomicNotes','TaxonomicSource', 'SISRecID','SpcRecID', 'Hyperlink'
]
data.columns = names
data.head()

,Order,Family name,Family,CommonName,ScientificName,Authority,TaxonomicTreatment,IUCNRedListCategory,Synonyms,AlternativeCommonNames,TaxonomicNotes,TaxonomicSource,SISRecID,SpcRecID,Hyperlink
1,STRUTHIONIFORMES,Struthionidae,Ostriches,Common Ostrich,Struthio camelus,"Linnaeus, 1758",R,LC,NaN,NaN,Struthio camelus and S. molybdophanes (del Hoy...,"del Hoyo, J., Collar, N.J., Christie, D.A., El...",45020636,1016860,http://datazone.birdlife.org/species/factsheet...
2,STRUTHIONIFORMES,Struthionidae,Ostriches,Somali Ostrich,Struthio molybdophanes,"Reichenow, 1883",R,VU,NaN,NaN,Struthio camelus and S. molybdophanes (del Hoy...,"del Hoyo, J., Collar, N.J., Christie, D.A., El...",22732795,31769,http://datazone.birdlife.org/species/factsheet...
3,STRUTHIONIFORMES,Struthionidae,Ostriches,NaN,Struthio camelus,"Linnaeus, 1758",NR,NR,NaN,Autruche,NaN,AERC TAC (2003); Christidis & Boles (2008); Cr...,22678068,1,http://datazone.birdlife.org/species/factsheet...
4,STRUTHIONIFORMES,Rheidae,Rheas,Greater Rhea,Rhea americana,"(Linnaeus, 1758)",R,NT,NaN,"Common Rhea, Avestruz, Ñandú, Ñandú Común",NaN,"del Hoyo, J., Collar, N.J., Christie, D.A., El...",22678073,2,http://datazone.birdlife.org/species/factsheet...
5,STRUTHIONIFORMES,Rheidae,Rheas,Lesser Rhea,Rhea pennata,"d'Orbigny, 1834",R,LC,NaN,NaN,Rhea pennata and R. tarapacensis (del Hoyo and...,"del Hoyo, J., Collar, N.J., Christie, D.A., El...",22728199,1016842,http://datazone.birdlife.org/species/factsheet...

In [48]:
data.to_csv("Birds.csv", index=False)
data.tail()

,Order,Family name,Family,CommonName,ScientificName,Authority,TaxonomicTreatment,IUCNRedListCategory,Synonyms,AlternativeCommonNames,TaxonomicNotes,TaxonomicSource,SISRecID,SpcRecID,Hyperlink
13038,PASSERIFORMES,Thraupidae,Tanagers,NaN,Tangara cyanoptera,"(Swainson, 1834)",NR,NR,NaN,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22722950,9428,http://datazone.birdlife.org/species/factsheet...
13039,PASSERIFORMES,Thraupidae,Tanagers,NaN,Tangara vassorii,"(Boissonneau, 1840)",NR,NR,NaN,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22722933,9423,http://datazone.birdlife.org/species/factsheet...
13040,PASSERIFORMES,Thraupidae,Tanagers,NaN,Tangara velia,"(Linnaeus, 1758)",NR,NR,NaN,NaN,NaN,"SACC (2005 & updates); Sibley & Monroe (1990, ...",22731274,31308,http://datazone.birdlife.org/species/factsheet...
13041,PASSERIFORMES,Thraupidae,Tanagers,NaN,Tangara brasiliensis,"(Linnaeus, 1766)",NR,NR,NaN,NaN,NaN,Stotz et al. (1996),22731781,31402,http://datazone.birdlife.org/species/factsheet...
13042,PASSERIFORMES,Thraupidae,Tanagers,NaN,Tangara cucullata,"(Swainson, 1834)",NR,NR,NaN,NaN,NaN,AOU (1998 & supplements); Sibley & Monroe (199...,22722887,9408,http://datazone.birdlife.org/species/factsheet...